<?php

declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$breadcrumbs = [['name' => 'Startseite', 'url' => site_url()], ['name' => 'Datenschutz', 'url' => site_url('datenschutz/')]];
site_header('datenschutz', ['breadcrumbs' => $breadcrumbs]);
render_breadcrumbs($breadcrumbs);
$operatorReady = operator_value('name') && operator_value('street') && operator_value('email');
?>
<main id="main-content">
    <section class="page-hero compact"><div class="wrap narrow"><p class="eyebrow">Datenschutzinformationen</p><h1>Datenschutzerklärung</h1><p class="lead">Diese Projektfassung beschreibt ausschließlich die derzeit technisch aktivierten Verarbeitungen. Sie benötigt vor Veröffentlichung eine rechtliche Prüfung und die Ergänzung der tatsächlichen Betreiber und Dienstleisterangaben.</p></div></section>
    <section class="section legal-page"><div class="wrap narrow">
        <?php if (!$operatorReady): ?><div class="notice warning"><strong>Prüfbedürftige Projektfassung:</strong> Verantwortlicher, Hosting, E Mail Dienst, Speicherfristen und Verträge zur Auftragsverarbeitung sind noch nicht abschließend konfiguriert.</div><?php endif; ?>
        <h2>1. Verantwortlicher</h2><p><?= e(operator_value('company') ?: 'Unternehmensbezeichnung vor Veröffentlichung ergänzen') ?><br><?= e(operator_value('name') ?: 'Name des Verantwortlichen vor Veröffentlichung ergänzen') ?><br><?= e(operator_value('street') ?: 'Anschrift vor Veröffentlichung ergänzen') ?><br><?= e(operator_value('email') ?: 'E Mail Adresse vor Veröffentlichung ergänzen') ?></p>
        <h2>2. Hosting und Serverprotokolle</h2><p>Beim Aufruf der Webseite verarbeitet der Webserver technisch erforderliche Verbindungsdaten. Dazu können Internet Protokoll Adresse, Zeitpunkt, angeforderte Adresse, übertragene Datenmenge, Statuscode, verweisende Seite sowie Browser und Betriebssystem gehören. Zweck ist die sichere und fehlerfreie Bereitstellung der Webseite.</p><p>Hostingdienst: <?= e($config['services']['hosting_provider']) ?><br>Verarbeitungsort: <?= e($config['services']['hosting_location']) ?><br>Speicherdauer der Serverprotokolle: vor Veröffentlichung mit dem Hostingdienst festlegen<br>Vertrag zur Auftragsverarbeitung: Abschluss und Inhalt vor Veröffentlichung prüfen</p><p>Als mögliche Rechtsgrundlage kommt das berechtigte Interesse an sicherer Bereitstellung nach Artikel 6 Absatz 1 Buchstabe f DSGVO in Betracht. Die abschließende Einordnung wird rechtlich geprüft.</p>
        <h2>3. Technisch erforderliche Sitzung</h2><p>Beim Aufruf eines Formulars verwendet die Webseite das Sitzungscookie <code>eeb_session</code>. Reine Informationsseiten setzen dieses Cookie nicht. Es enthält eine zufällige Sitzungskennung und ermöglicht Schutzmechanismen der Formulare, insbesondere den Schutz vor gefälschten Anfragen. Das Cookie wird beim Schließen des Browsers gelöscht. Es ist mit den Eigenschaften HttpOnly und SameSite Lax versehen. Bei verschlüsseltem Aufruf wird zusätzlich Secure gesetzt.</p><p>Die Sitzung speichert zeitlich begrenzt Schutzwerte für Formulare und nach erfolgreichem Versand eine einmalig angezeigte Bestätigung. Es werden keine Statistik, Marketing oder Personalisierungscookies eingesetzt. Die Speicherung ist für die ausdrücklich gewünschte Formularfunktion technisch erforderlich.</p>
        <h2>4. Kontaktformular</h2><p>Bei Nutzung des Kontaktformulars werden Name, E Mail Adresse, gewähltes Thema, Nachricht, Zeitpunkt und technisch erforderliche Sicherheitsdaten verarbeitet. Zweck ist die Bearbeitung Ihrer Nachricht. Empfänger ist ausschließlich der Portalbetreiber sowie der noch festzulegende E Mail Dienst als möglicher Auftragsverarbeiter.</p><p>Die Rechtsgrundlage richtet sich nach dem Anliegen. In Betracht kommen vorvertragliche Maßnahmen nach Artikel 6 Absatz 1 Buchstabe b DSGVO oder das berechtigte Interesse an der Bearbeitung von Anfragen nach Artikel 6 Absatz 1 Buchstabe f DSGVO. Eine pauschale Einwilligung wird nicht verlangt. Die genaue Speicherdauer und der Löschprozess werden vor Veröffentlichung festgelegt.</p>
        <h2>5. Anfrage zur Energieberatung</h2><p>Verarbeitet werden Gebäudeart, Postleitzahl, gegebenenfalls Baujahr, Anzahl der Einheiten, gewünschte Leistung, geplante Maßnahme, Beschreibung, Kontaktweg, Name, E Mail Adresse und freiwillig die Telefonnummer. Zweck ist die vom Nutzer gewünschte Einordnung und Kontaktaufnahme.</p><p>Im Ausgangszustand ist jede automatische Weitergabe deaktiviert. Bevor Daten an einen Energieberater übermittelt werden, wird der konkrete Empfänger benannt. Nutzer erfahren, welche Daten zu welchem Zweck weitergegeben werden, ob ein oder mehrere Anbieter beteiligt sind, welche Rechtsgrundlage vorgesehen ist und wo die Datenschutzhinweise des Empfängers erreichbar sind. Erst danach erfolgt eine gesonderte Bestätigung.</p>
        <h2>6. Anbieteranfrage</h2><p>Bei der Anbieteranfrage werden Unternehmensname, Kontaktperson, E Mail Adresse, freiwillige Webseitenadresse, freiwilliger Link zum offiziellen Listeneintrag und eine Leistungsbeschreibung verarbeitet. Zweck ist die Prüfung einer möglichen Aufnahme. Eine Veröffentlichung erfolgt nicht aufgrund des Formulars allein.</p><p>Vor einem Profil werden Richtigkeit, Veröffentlichungsberechtigung, Rechte an Logos und Bildern sowie die Information genannter Personen dokumentiert. Berichtigung und Löschung können verlangt werden.</p>
        <h2>7. E Mail Versand</h2><p>Der Versand ist in der ausgelieferten Projektfassung deaktiviert. Vor Aktivierung müssen folgender Dienst und alle Datenflüsse ergänzt werden:</p><p>E Mail Dienst: <?= e($config['services']['mail_provider']) ?><br>Verarbeitungsort: <?= e($config['services']['mail_location']) ?><br>Vertrag zur Auftragsverarbeitung: vor Aktivierung prüfen<br>Drittlandzugriff: vor Aktivierung prüfen<br>Speicher und Löschfristen: vor Aktivierung festlegen</p>
        <h2>8. Keine Analyse und keine externen Medien</h2><p>Es sind kein Webtracking, keine Werbepixel, keine externen Schriftarten, keine Karten, keine eingebetteten Videos, keine sozialen Plugins und keine Ressourcen von Inhaltsnetzwerken aktiviert. Es werden weder Local Storage noch Session Storage verwendet.</p>
        <h2>9. Empfänger und Drittlandübermittlung</h2><p>Außer den nach Konfiguration genannten Hosting und E Mail Dienstleistern sind keine Empfänger vorgesehen. Dienste mit Verarbeitung oder möglichem Zugriff außerhalb des Europäischen Wirtschaftsraums werden erst nach dokumentierter Prüfung und administrativer Freigabe aktiviert.</p>
        <h2>10. Löschung</h2><p>Konkrete Fristen werden anhand des tatsächlichen Bearbeitungsablaufs und gesetzlicher Aufbewahrungspflichten vor Veröffentlichung festgelegt. Bis dahin dürfen Formulare nicht produktiv aktiviert werden. Das interne Löschkonzept umfasst Kontaktanfragen, vermittelte Anfragen, Anbieteranfragen, Verträge, Rechnungen, Serverprotokolle, Einwilligungsnachweise, E Mail Korrespondenz, Sicherungskopien und mögliche Uploads.</p>
        <h2>11. Ihre Rechte</h2><p>Betroffene Personen haben nach Maßgabe der gesetzlichen Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kann mit Wirkung für die Zukunft widerrufen werden. Außerdem besteht ein Beschwerderecht bei einer zuständigen Datenschutzaufsichtsbehörde.</p><p>Der konkrete Kontaktweg für Datenschutzanliegen und die zuständige Aufsichtsbehörde werden nach Festlegung des Verantwortlichen ergänzt.</p>
        <h2>12. Sicherheit</h2><p>Die Webseite nutzt verschlüsselte Übertragung nach Einrichtung von HTTPS, sichere Sitzungseinstellungen, Schutzwerte gegen gefälschte Formularaufrufe, serverseitige Validierung, zeitbasierte Plausibilitätsprüfung, einen unsichtbaren Bot Schutz und eine Begrenzung wiederholter Anfragen. Sicherheitskopfzeilen begrenzen fremde Inhalte und Einbettung.</p>
        <h2>13. Stand und rechtliche Prüfung</h2><p>Stand dieser technischen Projektfassung: 21. Juli 2026. Die Erklärung ist vor Veröffentlichung durch eine fachkundige Stelle anhand der tatsächlichen Betreiberstruktur, Dienstleister, Verträge, Datenflüsse und Löschfristen zu prüfen.</p>
    </div></section>
</main>
<?php site_footer(); ?>
